src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable
 */
class Property
{

    const HEATER = [
        0 => 'Electric',
        1 => 'Gas'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @assert\Length(min=5, max=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @assert\Range(min=10, max="1500")
     */
    private $surface_area;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Choice(callback="assertHeat")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

     /**
     * @var File|null
     * @Assert\Image(mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_img", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct(){
        $this->create_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title); 
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurfaceArea(): ?int
    {
        return $this->surface_area;
    }

    public function setSurfaceArea(int $surface_area): self
    {
        $this->surface_area = $surface_area;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEATER[ $this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public static function assertHeat()
    {
        return array_flip(self::HEATER);
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): Property
    {
        $this->imageName = $imageName;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\ContactType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;


/**
 * Description of PropertyController
 *
 * @author amine
 */
class PropertyController extends AbstractController {
    
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManager
     */
    private $em;

    /**
     * class construct
     */
    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        // We used the dependency injection (autowiring)
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/property/list", name="property_index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request) : Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        //$properties = $this->repository->findAllVisible();
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search), 
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('property/index.html.twig', [
            'current_menu' => "property",
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }
    
    /**
     * @Route("/property/{slug}-{id}", name="property.show", requirements={"slug"="[a-z0-9\-]*"})
     * @param Property $property
     * @param string $slug
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request, ContactNotification $notification): Response
    {
         if($property->getSlug() !== $slug){
            return $this->redirectToRoute("property.show", [
                 'id' => $property->getId(),
                 'slug' => $property->getSlug()
             ], 301);
         }

        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $notification->notify($contact);
            $this->addFlash('success', "Your email  was successfully sent");
            return $this->redirectToRoute("property.show", [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }

        return $this->render('property/show.html.twig', [
            'current_menu' => "properties",
            'property' => $property,
            'form' => $form->createView()
        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.imageName %}
    <!--<img class="card-img-top" src="/images/properties/{{ property.imageName }}" style="width: 100%; height: auto;"/>-->
    <!-- <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" style="width: 100%; height: auto;"/> -->
    <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') }}" style="width: 100%; height: auto;"/>
    {% else %}
    <!-- <img class="card-img-top" src="{{ "/images/properties/empty.jpg" | imagine_filter('thumb')  }}" style="width: 100%; height: auto;"/> -->
    <img class="card-img-top" src="{{ "/images/properties/empty.jpg" }}" style="width: 100%; height: auto;"/>
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {id: property.id, slug: property.slug}) }}">
            {{ property.title }}
            </a>
        </h5>
        <p class="card-text">{{ property.surfaceArea }} m² - {{ property.city }} ( {{ property.zipCode }} )</p>
        <!-- <div class="text-primary">{{ property.price | number_format(0, '', ' ') }} €</div> -->
        <div class="text-primary" style="font-weight: bold;font-size: 2rem;">{{ property.formatedPrice }} €</div>
    </div>
</div>

templates/property/index.html.twig
{% extends "base.html.twig" %}

{% block title %} Property list {% endblock %}

{% block body %}

    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurfaceArea) }}
                </div>
                
                 <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>

                <div class="col">
                    {{ form_row(form.options) }}
                </div>

                 <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    <div class="container mt-4">
        <h1>Welcom to Proprety page</h1>

        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
                
            {% endfor %}
        </div>

         <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends "base.html.twig" %}

{% block title property.title %}

{% block body %}
        <div class="jumbotron">
            <div class="container">
                
                {{ include('generic/_flashes.html.twig') }}

                {% if not form.vars.valid %}
                    <div class="alert alert-danger">
                        An error has occurred !!!
                    </div>
                {% endif%}

                <div class="row">
                    <div class="col-md-8">
                         {% if property.imageName %}
                        <!-- <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium') }}" style="width: 100%; height: auto;"/> -->
                            <img class="card-img-top" src="{{ vich_uploader_asset(property, 'imageFile') }}" style="width: 100%; height: auto;"/>
                        {% else %}
                        <!-- <img class="card-img-top" src="{{ "/images/properties/empty.jpg" | imagine_filter('medium')  }}" style="width: 100%; height: auto;"/> -->
                        <img class="card-img-top" src="{{ "/images/properties/empty.jpg" }}" style="width: 100%; height: auto;"/>
                        {% endif %}
                    </div>
                    <div class="col-md-4">
                        <h1>{{ property.title }}</h1>
                        <h2>{{ property.rooms }} rooms - {{ property.surfaceArea }} m²</h2>
                        <div class="text-primary" style="font-size: 4rem; font-weight: bold;">
                            {{ property.formatedPrice }} DT
                        </div>
                        <a href="#" class="btn btn-primary">Contact agency</a>
                        <div id="contactForm" class="mt-4">
                             {{ form_start(form) }}
                             <div class="row">
                                <div class="col">{{form_row(form.firstname)}}</div>
                                <div class="col">{{form_row(form.lastname)}}</div>
                             </div>
                             <div class="row">
                                <div class="col">{{form_row(form.phone)}}</div>
                                <div class="col">{{form_row(form.email)}}</div>
                             </div>
                             {{form_rest(form)}}
                             <div class="form-group">
                                <button class="btn btn-primary" formnovalidate>Send</button>
                             </div>
                             {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
       <div class="container mt-4">
            
            <p>
                {{ property.description | nl2br }}
            </p>

            <div class="row">
                <div class="col-md-8">
                    <h2>More Details</h2>
                    <table class="table table-striped">
                        <tr>
                            <td>Living space</td>
                            <td>{{ property.surfaceArea }} m²</td>
                        </tr>
                        <tr>
                            <td>Rooms</td>
                            <td>{{ property.rooms }}</td>
                        </tr>
                        <tr>
                            <td>Bedrooms</td>
                            <td>{{ property.bedrooms }}</td>
                        </tr>
                        <tr>
                            <td>Floor</td>
                            <td>{{ property.floor }}</td>
                        </tr>
                        <tr>
                            <td>Heaheatert</td>
                            <td>{{ property.heatType }}</td>
                        </tr>

                    </table>
                </div>
                <div class="col-md-4">
                    <h2>Specificity</h2>
                    <ul class="list-group">
                        {%  for option in property.options %}
                            <li class="list-group-item">{{ option.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
    </div>

{% endblock %}